name: vdb_secure_token
description: SDK VDB Secure Token.
version: 1.0.8
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^9.1.1
  flutter:
    sdk: flutter
  loggy: ^2.0.3
  geolocator: ^10.1.0
  pointycastle: ^3.7.4
  # google_api_availability: ^5.0.0
  huawei_location: 6.12.0+301
  google_huawei_availability: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

index_generator:
  exclude:
    - '**.g.dart'
  indexes:
    - path: lib
      include:
        - 'src/*'